[package]
name = "tasko-terminal-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
tasko-shared = { path = "../shared" }
tui = "0.19.0"
tokio = { version = "1.27.0", features = ["full"] }
reqwest = {version = "0.11.6", features = ["json"]}